<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Altinn.ApiClients.Dialogporten" Version="1.121.3" />
        <PackageReference Include="Altinn.ApiClients.Maskinporten" Version="10.1.0" />
        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.2" />
        <PackageReference Include="Altinn.Platform.Storage.Interface" Version="4.7.1" />
        <PackageReference Include="Azure.Identity" Version="1.21.0" />
        <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Refit.HttpClientFactory" Version="10.2.0" />
        <PackageReference Include="DeterministicGuids" Version="1.0.11" />
        <PackageReference Include="WolverineFx.AzureServiceBus" Version="5.41.0" />
        <PackageReference Include="ZiggyCreatures.FusionCache.Locking.AsyncKeyed" Version="2.9.0" />
    </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Altinn.DialogportenAdapter.Contracts\Altinn.DialogportenAdapter.Contracts.csproj" />
	</ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Altinn.DialogportenAdapter.Integration.Tests"/>
        <InternalsVisibleTo Include="Altinn.DialogportenAdapter.Unit.Tests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>
</Project>
