<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Altinn.DialogportenAdapter.Integration.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Altinn.ApiClients.Dialogporten" Version="1.121.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Testcontainers.ServiceBus" Version="4.15.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" /> <!-- Transient from Testcontainers.ServiceBus. Forced upgrade due to CVE. Remove when patched -->
    <PackageReference Include="WireMock.Net" Version="2.18.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Altinn.DialogportenAdapter.Contracts/Altinn.DialogportenAdapter.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Altinn.DialogportenAdapter.WebApi/Altinn.DialogportenAdapter.WebApi.csproj" />
    <ProjectReference Include="..\Altinn.DialogportenAdapter.Test.Common\Altinn.DialogportenAdapter.Test.Common.csproj" />
  </ItemGroup>

</Project>
